// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinLanka.Server.Data;

#nullable disable

namespace WinLanka.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924153137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinLanka.Server.Models.DispatchItem", b =>
                {
                    b.Property<int>("DispatchItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispatchItemId"));

                    b.Property<int>("DispatchNoteId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockItemId")
                        .HasColumnType("int");

                    b.HasKey("DispatchItemId");

                    b.HasIndex("DispatchNoteId");

                    b.HasIndex("StockItemId");

                    b.ToTable("DispatchItems");
                });

            modelBuilder.Entity("WinLanka.Server.Models.DispatchNote", b =>
                {
                    b.Property<int>("DispatchNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispatchNoteId"));

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("DispatchNoteId");

                    b.ToTable("DispatchNotes");
                });

            modelBuilder.Entity("WinLanka.Server.Models.GRNItem", b =>
                {
                    b.Property<int>("GRNItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRNItemId"));

                    b.Property<int>("GRNId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockItemId")
                        .HasColumnType("int");

                    b.HasKey("GRNItemId");

                    b.HasIndex("GRNId");

                    b.HasIndex("StockItemId");

                    b.ToTable("GRNItems");
                });

            modelBuilder.Entity("WinLanka.Server.Models.GoodReceivedNote", b =>
                {
                    b.Property<int>("GoodReceivedNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodReceivedNoteId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoodReceivedNoteId");

                    b.ToTable("GoodReceivedNotes");
                });

            modelBuilder.Entity("WinLanka.Server.Models.Scope", b =>
                {
                    b.Property<int>("ScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScopeId"));

                    b.Property<string>("ScopeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScopeId");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("WinLanka.Server.Models.StockItem", b =>
                {
                    b.Property<int>("StockItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockItemId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockItemId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("WinLanka.Server.Models.StockSum", b =>
                {
                    b.Property<int>("StockSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockSummaryId"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockItemId")
                        .HasColumnType("int");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDispatched")
                        .HasColumnType("int");

                    b.Property<int>("TotalReceived")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockSummaryId");

                    b.HasIndex("StockItemId")
                        .IsUnique();

                    b.ToTable("StockSums");
                });

            modelBuilder.Entity("WinLanka.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WinLanka.Server.Models.UserScope", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("UserScopes");
                });

            modelBuilder.Entity("WinLanka.Server.Models.DispatchItem", b =>
                {
                    b.HasOne("WinLanka.Server.Models.DispatchNote", "DispatchNote")
                        .WithMany("DispatchItems")
                        .HasForeignKey("DispatchNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinLanka.Server.Models.StockItem", "StockItem")
                        .WithMany("DispatchItems")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispatchNote");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("WinLanka.Server.Models.GRNItem", b =>
                {
                    b.HasOne("WinLanka.Server.Models.GoodReceivedNote", "GRN")
                        .WithMany("GRNItems")
                        .HasForeignKey("GRNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinLanka.Server.Models.StockItem", "StockItem")
                        .WithMany("GRNItems")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GRN");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("WinLanka.Server.Models.StockSum", b =>
                {
                    b.HasOne("WinLanka.Server.Models.StockItem", null)
                        .WithOne()
                        .HasForeignKey("WinLanka.Server.Models.StockSum", "StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinLanka.Server.Models.UserScope", b =>
                {
                    b.HasOne("WinLanka.Server.Models.Scope", "Scope")
                        .WithMany("UserScopes")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinLanka.Server.Models.User", "User")
                        .WithMany("UserScopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WinLanka.Server.Models.DispatchNote", b =>
                {
                    b.Navigation("DispatchItems");
                });

            modelBuilder.Entity("WinLanka.Server.Models.GoodReceivedNote", b =>
                {
                    b.Navigation("GRNItems");
                });

            modelBuilder.Entity("WinLanka.Server.Models.Scope", b =>
                {
                    b.Navigation("UserScopes");
                });

            modelBuilder.Entity("WinLanka.Server.Models.StockItem", b =>
                {
                    b.Navigation("DispatchItems");

                    b.Navigation("GRNItems");
                });

            modelBuilder.Entity("WinLanka.Server.Models.User", b =>
                {
                    b.Navigation("UserScopes");
                });
#pragma warning restore 612, 618
        }
    }
}
